# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7fb64970f9af96a8a179530cfa3c60b5e39af15960816daaf942c86ba0a57f7e040e45327675bdb1b7a16a44e37d9cd106b4de1cf946402371e5aac22a5f9d40

test:
  secret_key_base: 53edec0ebc187c015b6c953d7dd6917a65e6dfc24b8408700b3b3027b413270a64dfe15dbb6996e8166d2f74030b1ac49c7fa509789f5a02f3638cc47f864fd3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
